base:
  project: Insurance Predictor
  random_state: 42
  target_col: expenses

data_source:
  s3_source: data_given/insurance.csv

load_data:
  raw_dataset_csv: data/raw/insurance.csv

split_data:
  train_path: data/processed/train_insurance.csv
  test_path: data/processed/test_insurance.csv
  test_size: 0.05

clean_data:
  train_path: data/cleaned/train_insurance.csv
  test_path: data/cleaned/test_insurance.csv

estimators:
  DecisionTreeRegressor:
    params:
      max_depth: 5
      min_samples_split: 20
      #alpha: 0.9
      #sl1_ratio: 0.4
model_dir: saved_models
